#!/bin/bash
set -e

appStart () {
  echo "Starting OpenAM..."
  chown -R tomcat7:tomcat7 /usr/share/tomcat7/
  chown -R tomcat7:tomcat7 /usr/share/tomcat7/config
  chown -R tomcat7:tomcat7 /usr/share/tomcat7/opt/
  /etc/init.d/tomcat7 start && wait && /etc/init.d/apache2 start && wait && tail -f /var/log/tomcat7/catalina.out
  cd /sbin/; ./my_init
  
}

appHelp () {
  echo "Available options:"
  echo " app:start          - Starts the gitlab-ci server (default)"
  echo " app:help           - Displays the help"
#  echo " [command]          - Execute the specified linux command eg. bash."
}

case "$1" in
  app:start)
#    appStart
    ;;
  app:help)
#    appHelp
    ;;
  *)
	appStart
  ;;
esac

exit 0
